[workspace]
authors = ["Neppel Elian <elian.neppel@posteo.eu>"]
channels = ["conda-forge"]
name = "cydr"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
bench-joint-state-cython = "python -m bench.joint_state_cython_serialization"
bench-every-supported-cython = "python -m bench.every_supported_cython_serialization"
bench-fixed-arrays-cython = "python -m bench.fixed_arrays_cython_serialization"
bench-primitive-matrix-cython = "python -m bench.primitive_matrix_cython_serialization"

[dependencies]
python = "3.13.*"
numpy = ">=2.4.3,<3"
pyright = "*"
isort = "*"
black = "*"
pytest = "*"
colorama = "*"
cython = "*"
glow-md = "*"
msgspec = "*"

[pypi-dependencies]
cyclonedds-idl = ">=0.1.0, <0.2"
cydr = { path = ".", editable = true }
np2typing = "*"
